# Generated by Django 5.1.2 on 2025-10-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
            ],
        ),
    ]
