# Generated by Django 5.1.2 on 2025-10-07 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('grade_course', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecourse',
            options={'ordering': ['grade__name', 'course__name'], 'verbose_name': 'Grade Course', 'verbose_name_plural': 'Grade Courses'},
        ),
        migrations.AddField(
            model_name='gradecourse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gradecourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gradecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='gradecourse',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_courses', to='grades.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='gradecourse',
            unique_together={('grade', 'course')},
        ),
        migrations.AlterModelTable(
            name='gradecourse',
            table='grade_courses',
        ),
    ]
